name: Train ML Model

on:
  push:
    paths:
      - 'MLProject/**'

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        environment-file: MLProject/conda.yaml
        activate-environment: mlflow-env

    - name: Install MLflow
      run: pip install mlflow

    - name: Run MLflow Project
      working-directory: MLProject
      run: mlflow run . --entry-point main
